---
title: "Introduction to the Labs"
author: "Emilio Dorigatti"
date: 2021-10-19
output:
  beamer_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Labs

 - Mix of theoretical and practical exercises
 - Not graded! Only final exam counts
 - Exercises and solutions for the previous week posted on Moodle on Tuesday morning
 - I will present questions for the week and solutions for the previous week on Friday
 - Second part of the lab for free form discussions or we end early if there are no topics
 - Lab sessions exist to discuss and ask questions, attend not to fall behind the schedule

## Theory-oriented Exercises

 - Apply the math you see in the lectures
    - Pen-and-paper exercises on simple cases
    - Code the solution and test on simple problems
    - Brush up your linear algebra!
 - Purpose:
   1. Understand and internalize how things work
   2. Get practical experience in implementing ML algorithms
   3. Get ready for the exam

## Practice-oriented Exercises

 - Play with neural networks
   - github.com/jjallaire/deep-learning-with-r-notebooks
   - github.com/fchollet/deep-learning-with-python-notebooks
 - Handouts both in in R and Python
   - I will present the solutions in R, but you are free to use and ask questions about the Python version
 - Purpose:
   1. Learn to use a popular Deep Learning Framework
      - For R we will use Keras/Tensorflow
      - For Python we will use PyTorch
   2. Get a feeling for how neural networks behave

## Our software stack (R)

 1. Keras for R
 2. Keras for Python
 3. Tensorflow (Python bindings)
 4. Tensorflow (C++)
      - CPU computations: BLAS (C/Fotran)
      - GPU computations: cuDNN (C)
      - TPU computations: Private Google library
